# generated by datamodel-codegen:
#   filename:  all_schemas.json
#   timestamp: 2026-06-03T11:34:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class Model(RootModel[Any]):
    root: Any


class DemoMessagePayload(BaseModel):
    """
    Payload for simple pub/sub messages
    """

    text: str = Field(..., description="The message text content")
    timestamp: AwareDatetime = Field(..., description="When the message was created")


class RequestPayload(BaseModel):
    """
    Payload for request messages
    """

    request_id: str = Field(..., description="Unique identifier for the request")
    data: str = Field(..., description="Request data to be processed")
    timestamp: AwareDatetime = Field(..., description="When the request was created")


class ResponsePayload(BaseModel):
    """
    Payload for response messages
    """

    request_id: str = Field(..., description="ID of the request being responded to")
    result: str = Field(..., description="Processing result")
    timestamp: AwareDatetime = Field(..., description="When the response was created")


class Priority(Enum):
    """
    Message priority
    """

    low = "low"
    normal = "normal"
    high = "high"


class Metadata(BaseModel):
    """
    Additional metadata
    """

    source: str = Field(..., description="Source of the message")
    priority: Priority | None = Field(None, description="Message priority")


class StreamMessagePayload(BaseModel):
    """
    Payload for JetStream persistent messages
    """

    message_id: str = Field(..., description="Unique identifier for the message")
    data: str = Field(..., description="Message data")
    metadata: Metadata | None = Field(None, description="Additional metadata")
    timestamp: AwareDatetime = Field(..., description="When the message was created")
